In [27]:
import pandas as pd
import os
import sys
sys.path.append(os.path.abspath("E:\de_work\project\mini\etl_basic").replace("\\", "/"))
from src.extract import fetch_users, get_data_csv

<>:4: SyntaxWarning: invalid escape sequence '\d'
<>:4: SyntaxWarning: invalid escape sequence '\d'
C:\Users\HieuHuynh_DE\AppData\Local\Temp\ipykernel_10064\709456087.py:4: SyntaxWarning: invalid escape sequence '\d'
  sys.path.append(os.path.abspath("E:\de_work\project\mini\etl_basic").replace("\\", "/"))

In [28]:
df_api = fetch_users()
df_csv = pd.read_csv('../../data/orders.csv')

Status code: 200

In [29]:
df_api

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"{'street': 'Victor Plains', 'suite': 'Suite 87...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"{'street': 'Douglas Extension', 'suite': 'Suit...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"{'street': 'Hoeger Mall', 'suite': 'Apt. 692',...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"{'street': 'Skiles Walks', 'suite': 'Suite 351...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."
5,6,Mrs. Dennis Schulist,Leopoldo_Corkery,Karley_Dach@jasper.info,"{'street': 'Norberto Crossing', 'suite': 'Apt....",1-477-935-8478 x6430,ola.org,"{'name': 'Considine-Lockman', 'catchPhrase': '..."
6,7,Kurtis Weissnat,Elwyn.Skiles,Telly.Hoeger@billy.biz,"{'street': 'Rex Trail', 'suite': 'Suite 280', ...",210.067.6132,elvis.io,"{'name': 'Johns Group', 'catchPhrase': 'Config..."
7,8,Nicholas Runolfsdottir V,Maxime_Nienow,Sherwood@rosamond.me,"{'street': 'Ellsworth Summit', 'suite': 'Suite...",586.493.6943 x140,jacynthe.com,"{'name': 'Abernathy Group', 'catchPhrase': 'Im..."
8,9,Glenna Reichert,Delphine,Chaim_McDermott@dana.io,"{'street': 'Dayna Park', 'suite': 'Suite 449',...",(775)976-6794 x41206,conrad.com,"{'name': 'Yost and Sons', 'catchPhrase': 'Swit..."
9,10,Clementina DuBuque,Moriah.Stanton,Rey.Padberg@karina.biz,"{'street': 'Kattie Turnpike', 'suite': 'Suite ...",024-648-3804,ambrose.net,"{'name': 'Hoeger LLC', 'catchPhrase': 'Central..."

In [7]:
df_api.columns.tolist()

['id', 'name', 'username', 'email', 'address', 'phone', 'website', 'company']

In [31]:
df_api = df_api.rename(columns = {"id": "user_id" , "name" : "customer_name"})

In [32]:
df_api['user_id'] = 'uc' + df_api['user_id'].astype(str)

In [33]:
df_api['city'] = df_api.apply(lambda row: row['address']['city'], axis=1)
df_api['company_name'] = df_api.apply(lambda row: row['company']['name'], axis=1)

In [35]:
df_api_main = df_api[['user_id', 'customer_name','email','phone', 'city', 'company_name']]

In [36]:
df_csv['user_id'] = 'uc' + df_csv['user_id'].astype(str)

In [37]:
df_api_main

,user_id,customer_name,email,phone,city,company_name
0,uc1,Leanne Graham,Sincere@april.biz,1-770-736-8031 x56442,Gwenborough,Romaguera-Crona
1,uc2,Ervin Howell,Shanna@melissa.tv,010-692-6593 x09125,Wisokyburgh,Deckow-Crist
2,uc3,Clementine Bauch,Nathan@yesenia.net,1-463-123-4447,McKenziehaven,Romaguera-Jacobson
3,uc4,Patricia Lebsack,Julianne.OConner@kory.org,493-170-9623 x156,South Elvis,Robel-Corkery
4,uc5,Chelsey Dietrich,Lucio_Hettinger@annie.ca,(254)954-1289,Roscoeview,Keebler LLC
5,uc6,Mrs. Dennis Schulist,Karley_Dach@jasper.info,1-477-935-8478 x6430,South Christy,Considine-Lockman
6,uc7,Kurtis Weissnat,Telly.Hoeger@billy.biz,210.067.6132,Howemouth,Johns Group
7,uc8,Nicholas Runolfsdottir V,Sherwood@rosamond.me,586.493.6943 x140,Aliyaview,Abernathy Group
8,uc9,Glenna Reichert,Chaim_McDermott@dana.io,(775)976-6794 x41206,Bartholomebury,Yost and Sons
9,uc10,Clementina DuBuque,Rey.Padberg@karina.biz,024-648-3804,Lebsackbury,Hoeger LLC

In [38]:
df_csv

   order_id user_id       product  quantity  price  order_date
0         1     uc1        Laptop         1   1200  2026-04-01
1         2     uc2         Mouse         2     25  2026-04-01
2         3     uc1      Keyboard         1     80  2026-04-02
3         4     uc3       Monitor         2    300  2026-04-02
4         5     uc4     USB Cable         5     10  2026-04-03
5         6    uc99     Headphone         1    150  2026-04-03
6         7     uc2  Laptop Stand         1     45  2026-04-04
7         8     uc3     Mouse Pad         3     12  2026-04-04

In [39]:
df_fact_sales = pd.merge(df_csv, df_api_main, left_on= 'user_id', right_on= 'user_id', how = 'left')

In [41]:
df_fact_sales

,order_id,user_id,product,quantity,price,order_date,customer_name,email,phone,city,company_name
0,1,uc1,Laptop,1,1200,2026-04-01,Leanne Graham,Sincere@april.biz,1-770-736-8031 x56442,Gwenborough,Romaguera-Crona
1,2,uc2,Mouse,2,25,2026-04-01,Ervin Howell,Shanna@melissa.tv,010-692-6593 x09125,Wisokyburgh,Deckow-Crist
2,3,uc1,Keyboard,1,80,2026-04-02,Leanne Graham,Sincere@april.biz,1-770-736-8031 x56442,Gwenborough,Romaguera-Crona
3,4,uc3,Monitor,2,300,2026-04-02,Clementine Bauch,Nathan@yesenia.net,1-463-123-4447,McKenziehaven,Romaguera-Jacobson
4,5,uc4,USB Cable,5,10,2026-04-03,Patricia Lebsack,Julianne.OConner@kory.org,493-170-9623 x156,South Elvis,Robel-Corkery
5,6,uc99,Headphone,1,150,2026-04-03,NaN,NaN,NaN,NaN,NaN
6,7,uc2,Laptop Stand,1,45,2026-04-04,Ervin Howell,Shanna@melissa.tv,010-692-6593 x09125,Wisokyburgh,Deckow-Crist
7,8,uc3,Mouse Pad,3,12,2026-04-04,Clementine Bauch,Nathan@yesenia.net,1-463-123-4447,McKenziehaven,Romaguera-Jacobson

In [42]:
df_fact_sales = df_fact_sales.fillna('Unknown')

In [43]:
df_fact_sales['total_amount'] = df_fact_sales['quantity'] * df_fact_sales['price']

In [44]:
df_fact_sales.columns.to_list()

['order_id',
 'user_id',
 'product',
 'quantity',
 'price',
 'order_date',
 'customer_name',
 'email',
 'phone',
 'city',
 'company_name',
 'total_amount']

In [45]:
df_fact_sales['order_date'] = pd.to_datetime(df_fact_sales['order_date'])
df_fact_sales['order_month'] = df_fact_sales['order_date'].dt.strftime("%Y-%m")

In [46]:
df_fact_sales

,order_id,user_id,product,quantity,price,order_date,customer_name,email,phone,city,company_name,total_amount,order_month
0,1,uc1,Laptop,1,1200,2026-04-01,Leanne Graham,Sincere@april.biz,1-770-736-8031 x56442,Gwenborough,Romaguera-Crona,1200,2026-04
1,2,uc2,Mouse,2,25,2026-04-01,Ervin Howell,Shanna@melissa.tv,010-692-6593 x09125,Wisokyburgh,Deckow-Crist,50,2026-04
2,3,uc1,Keyboard,1,80,2026-04-02,Leanne Graham,Sincere@april.biz,1-770-736-8031 x56442,Gwenborough,Romaguera-Crona,80,2026-04
3,4,uc3,Monitor,2,300,2026-04-02,Clementine Bauch,Nathan@yesenia.net,1-463-123-4447,McKenziehaven,Romaguera-Jacobson,600,2026-04
4,5,uc4,USB Cable,5,10,2026-04-03,Patricia Lebsack,Julianne.OConner@kory.org,493-170-9623 x156,South Elvis,Robel-Corkery,50,2026-04
5,6,uc99,Headphone,1,150,2026-04-03,Unknown,Unknown,Unknown,Unknown,Unknown,150,2026-04
6,7,uc2,Laptop Stand,1,45,2026-04-04,Ervin Howell,Shanna@melissa.tv,010-692-6593 x09125,Wisokyburgh,Deckow-Crist,45,2026-04
7,8,uc3,Mouse Pad,3,12,2026-04-04,Clementine Bauch,Nathan@yesenia.net,1-463-123-4447,McKenziehaven,Romaguera-Jacobson,36,2026-04

In [48]:
columns_list = ['order_id','user_id','customer_name','city', 'product', 'quantity','total_amount', 'order_month']
df_fact_sales = df_fact_sales[columns_list]

In [49]:
df_fact_sales

,order_id,user_id,customer_name,city,product,quantity,total_amount,order_month
0,1,uc1,Leanne Graham,Gwenborough,Laptop,1,1200,2026-04
1,2,uc2,Ervin Howell,Wisokyburgh,Mouse,2,50,2026-04
2,3,uc1,Leanne Graham,Gwenborough,Keyboard,1,80,2026-04
3,4,uc3,Clementine Bauch,McKenziehaven,Monitor,2,600,2026-04
4,5,uc4,Patricia Lebsack,South Elvis,USB Cable,5,50,2026-04
5,6,uc99,Unknown,Unknown,Headphone,1,150,2026-04
6,7,uc2,Ervin Howell,Wisokyburgh,Laptop Stand,1,45,2026-04
7,8,uc3,Clementine Bauch,McKenziehaven,Mouse Pad,3,36,2026-04